excludeLabels:
  - pinned
custom:
  - location: title
    keywords:
      - 'tweakers'
    labels:
      - duplicate
  - location: body
    keywords:
      - 'Remove this line, if you thruthfully filled in the Prerequisites'
    labels:
      - invalid
