excludeLabels:
  - ongoing
custom:
  - location: title
    keywords:
      - 'tweakers'
      - 'test'
    labels:
      - duplicate
  - location: body
    keywords:
      - 'Remove this line, if you thruthfully filled in the Prerequisites'
    labels:
      - invalid
