name: EasyDutch (NSFW)
description: Issue tracker for EasyDutch (NSFW)
title: "[NSFW]"
labels: NSFW
body:
  - type: checkboxes
    attributes:
      label: Prerequisites / Vereisten
      description: To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: This is a **Dutch** website / Het is een **Nederlandse** website
          required: true
        - label: I performed a [cursory search of the issue tracker](https://github.com/EasyDutch-uBO/EasyDutch/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
          required: true
        - label: Only ads or anti-adblock / Alleen advertenties of anti-adblock
          required: true
        - label: Filters were [updated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) before reproducing an issue / Filterlijsten zijn [geüpdated](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) voordat dit probleem werd gereproduceerd
          required: true
        - label: I have updated my browser to the most recent version / Ik heb mijn browser geüpdated naar de meest recente verie
          required: false
    
  - type: checkboxes
    attributes:
      label: I tried to reproduce the issue when...
      options:
        - label: uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
          required: true
        - label: uBlock Origin is the only extension / uBlock Origin is de enige extensie
          required: true

  - type: input
    attributes:
      label: URL(s) where the issue occurs / Website(s) waar het probleem voorkomt
      description: |
        At least one URL for a web page where the clearly described issue occurs is **mandatory**. 
        The backticks (`) surrounding the URLs are important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.
        Geef de link van de website waar het probleem zich voordoet. 
        Zorg er voor dat de URL niet klikbaar is. Waarschuw met "NSFW" als dat nodig is.
      placeholder: "`https://example.nl`; `https://example.be`"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.
        Wees zo duidelijk mogelijk: niemand kan je gedachten lezen en niemand kijkt over je schouder mee.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) for **difficult to describe visual issues are mandatory**. 
        Post **links** instead of inline images for screenshots containing **Adult material**.
        Is het **Volwassen materiaal** post dan linkjes in plaats van **Inline Images**.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Configuration / Configuratie
      description: | 
        List all the changes you've made to uBO's default settings here, by copying the information given by uBO's Dashboard under `Support` --> `Troubleshooting Information`
        Geef hier een lijst van alle wijzigingen die u heeft aangebracht in de standaardinstellingen van uBO, door de informatie te kopiëren die door uBO's Dashboard is gegeven onder `Ondersteuning` --> `Probleemoplossingsinformatie` 
      value: |
        <details>
        <summary>Troubleshooting Information / Probleemoplossingsinformatie</summary>
        
        ```yaml
        <!-- Put the copied text here, by replacing this line / Zet hier de gekopieerde tekst neer, door deze regel te overschrijven -->
        ```
        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes
      description: |
        Please investigate the issues you report -- this prevents burdening other volunteers. 
        This is especially true for issues arising from settings which are very different from default ones.
      placeholder: |
        Write here the result of whatever investigation work you have done
        Schrijf hier het resultaat van het onderzoekswerk dat je hebt gedaan
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Privacy
      description: |
        By submitting this issue, you agree that report does not contain private info, also not in the screenshots
        Dit issue bevat geen persoonlijke informatie, ook niet in de screenshots
      options:
        - label: I agree to follow this condition / Ik ga akkoord met deze voorwaarde
          required: true
