name: Improvements
description: Improvements or additions to documentation. You can also ask it in [Discussions](https://github.com/EasyDutch-uBO/EasyDutch/discussions) 
labels: documentation
body:
  - type: checkboxes
    attributes:
      label: Prerequisites / Vereisten
      description: To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: I performed a [cursory search of the issue tracker](https://github.com/BPower0036/AdBlockFilters/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
          required: true
    
  - type: textarea
    attributes:
      label: Describe the issue
      description: |
        Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.
        Wees zo duidelijk mogelijk: niemand kan je gedachten lezen en niemand kijkt over je schouder mee.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes
      description: |
        Possible solution for the problem.
        Mogelijk oplossing voor het probleem.
      placeholder: |
        Write here the result of whatever investigation work you have done
        Schrijf hier het resultaat van het onderzoekswerk dat je hebt gedaan
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshot(s)
    validations:
      required: false
