name: Update EasyDutch CDN

on:
  push:
    branches:
      - pre-gh-pages
  workflow_dispatch:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Update EasyDutch CDN
    runs-on: ubuntu-latest
    steps:
      - name: Repo check
        run: |
          if [[ "$GITHUB_REPOSITORY_OWNER" != "EasyDutch-uBO" ]]; then
            echo "This GitHub Action is meant to deliver filter lists for EasyDutch."
            echo "You shouldn't need to run this GitHub Action in your fork."
            echo "If you do, please customize the cron expression above, and the URLs below."
            exit 1
          fi
          exit 0
      - name: Clone EasyDutch
        uses: actions/checkout@v3
      - name: Generate version string
        run: |
          TAGNAME=$(date -u "+%Y.%-m.%-d.")$(date -u "+%H*60+%M" | bc)
          echo "TAGNAME=$TAGNAME" >> $GITHUB_ENV
          echo "Version string is $TAGNAME"
      - name: Copy shell script from uBlockOrigin/uAssets
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 --single-branch --branch=master https://github.com/uBlockOrigin/uAssets.git $TMPDIR
          cp -v $TMPDIR/tools/make-diffpatch.sh .
          cp -v $TMPDIR/tools/update-diffpatches.sh .
      - name: Copy EasyDutch filters to EasyDutchCDN
        run: |
          TMPFILE=$(mktemp -d)
          git clone --depth=1 --single-branch --branch=pre-gh-pages https://github.com/EasyDutch-uBO/EasyDutch.git $TMPFILE
          cp $TMPFILE/EasyDutch/*.txt EasyDutch/
          cp $TMPFILE/EasyDutch.txt EasyDutch.txt
          cp $TMPFILE/EasyDutch.all.txt EasyDutch.all.txt
      - name: Create new patch
        run: |
          ./make-diffpatch.sh "${{ env.TAGNAME }}"
      - name: Update existing patch
        run: |
          ./update-diffpatches.sh "${{ env.TAGNAME }}"
      - name: Commit changes (if any)
        run: |
          if [[ -z $(git diff --name-only --cached) ]]; then exit 0; fi
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git commit -m "Update modified filter lists"
          git push origin main
          git tag ${{ env.TAGNAME }}
          git push origin ${{ env.TAGNAME }}
